#!/bin/sh
#PBS -q normal
#PBS -N "splotch"
#PBS -l select=1:ncpus=1:mem=50GB
#PBS -l walltime=30:00:00

#PBS -e /home/jun.xu/logs
#PBS -o /home/jun.xu/logs

source activate jon
export R_LIBS=/shares/common/users/jun.xu/R_3.6.0.a
module load R/3.6.0

cd /home/jun.xu/gih/spa/data/hpdt_count_tables

for file in *tissue.tsv
do
  Rscript /home/jun.xu/gih/spa/de/splotch/prep.r $file
done

splotch_prepare_count_files -c *_splotch
Rscript /home/jun.xu/gih/spa/de/splotch/meta.r
splotch_generate_input_files -c *.unified.tsv -m metadata.tsv -s 2389.0 -l 3 -o data_three
